import {
    Box,
    Button,
    Container,
    Flex,
    Input,
    Spinner,
    Stack,
    Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Wrapper } from "../components/Wrapper";
import { withApollo } from "../utils/withApollo";
import { useSearchQuery } from "../generated/graphql";
import { useState } from "react";

const Home: NextPage = () => {
    const [query, setQuery] = useState<string>("large");
    const searchQuery = useSearchQuery({ variables: { search: query } });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Wrapper>
                <Text fontSize="xl">Pokemon finder thing</Text>

                <Input
                    name="search"
                    placeholder="search"
                    size="lg"
                    onChange={(event) => setQuery(event.target.value)}
                    value={query}
                />

                {searchQuery.loading ? (
                    <Spinner />
                ) : (
                    <Stack>
                        {searchQuery.data?.search.map((p) => (
                            <Flex
                                key={p.id}
                                p={5}
                                shadow="md"
                                borderWidth="1px"
                                flexDirection="column"
                            >
                                <Text fontSize="2xl">{p.name}</Text>
                                <Text>
                                    {p.type_1} and {p.type_2}
                                </Text>
                                <Text>{p.description}</Text>
                            </Flex>
                        ))}
                    </Stack>
                )}
            </Wrapper>
        </>
    );
};

export default withApollo({ ssr: true })(Home);
